;(function () {
  "use strict"
  const q = (theme, question, choices, answer, explanation) => ({
    theme,
    question,
    choices,
    answer,
    explanation,
  })

  window.linuxQuizBanks = {
    "00-mise-en-place": {
      id: "00-mise-en-place",
      chapter: "Chapitre 00 · Préparation",
      title: "Mise en place du laboratoire",
      intro:
        "Validez l'architecture VirtualBox, l'adressage de la VM et les premiers réflexes de vérification avant de déployer les services.",
      chapterLink: "./",
      questions: [
        q(
          "Architecture",
          "Quel est le rôle principal de la carte réseau en mode NAT dans le laboratoire ?",
          [
            "Fournir une adresse publique fixe à la VM",
            "Donner à la VM un accès sortant vers Internet",
            "Relier uniquement la VM à l'hôte",
            "Remplacer le pare-feu Linux",
          ],
          1,
          "Le NAT VirtualBox fournit généralement l'accès sortant nécessaire aux mises à jour, sans exposer directement la VM sur le réseau physique.",
        ),
        q(
          "Architecture",
          "Pourquoi ajouter une seconde carte sur un réseau privé hôte ?",
          [
            "Pour disposer d'un lien stable entre l'hôte et la VM",
            "Pour doubler automatiquement le débit Internet",
            "Pour éviter toute adresse IP",
            "Pour installer GRUB sur le réseau",
          ],
          0,
          "Le réseau privé hôte permet à la machine physique et à la VM de communiquer sur un segment isolé et prévisible.",
        ),
        q(
          "Adressage",
          "Quelle adresse statique est prévue pour l'interface enp0s8 du serveur de laboratoire ?",
          ["10.0.2.15/8", "127.0.0.1/8", "192.168.56.200/24", "172.16.0.200/16"],
          2,
          "Le fil rouge utilise 192.168.56.200/24 sur enp0s8 afin de conserver la même cible pour SSH et les futurs services.",
        ),
        q(
          "Commandes",
          "Quelle commande affiche les interfaces et leurs adresses sous une forme brève et colorée ?",
          ["ip -c -br address", "route --services", "lsblk -f", "systemctl network"],
          0,
          "ip -c -br address, abrégé en ip -c -br a, donne une vue synthétique de l'état et des adresses des interfaces.",
        ),
        q(
          "Diagnostic",
          "Après ifup enp0s8, quel résultat constitue la meilleure première preuve ?",
          [
            "Le fichier de configuration existe",
            "L'interface apparaît UP avec 192.168.56.200/24",
            "La VM possède deux processeurs",
            "Le service Apache répond",
          ],
          1,
          "La configuration écrite est une intention ; l'état UP et l'adresse observée avec ip prouvent qu'elle a été appliquée.",
        ),
        q(
          "Réseau",
          "À quoi correspond le préfixe /24 de 192.168.56.200/24 ?",
          ["24 hôtes maximum", "24 routes par défaut", "Un masque 255.255.255.0", "Le port SSH"],
          2,
          "Un préfixe IPv4 /24 fixe 24 bits pour le réseau, soit le masque 255.255.255.0.",
        ),
        q(
          "SSH",
          "Quelle commande teste la connexion distante prévue depuis l'hôte ?",
          [
            "ssh stagiaire@192.168.56.200",
            "ssh root@127.0.0.1",
            "telnet 192.168.56.200 80",
            "ping ssh://stagiaire",
          ],
          0,
          "Cette commande teste à la fois la joignabilité IP, l'écoute de SSH et l'authentification du compte stagiaire.",
        ),
        q(
          "Méthode TSSR",
          "Pourquoi tester SSH avant de fermer la console de la VM ?",
          [
            "Pour installer automatiquement Debian",
            "Pour conserver un accès de secours si la configuration distante échoue",
            "Pour désactiver le réseau privé",
            "Pour créer une sauvegarde LVM",
          ],
          1,
          "Il faut valider le nouvel accès avant d'abandonner l'accès existant ; la console reste une voie de secours essentielle.",
        ),
        q(
          "Configuration",
          "Quel fichier Debian est modifié dans le cours pour configurer enp0s8 ?",
          ["/etc/network/interfaces", "/etc/hosts.allow", "/boot/grub/grub.cfg", "/etc/fstab"],
          0,
          "/etc/network/interfaces décrit ici l'activation automatique et l'adresse statique de l'interface.",
        ),
        q(
          "Configuration",
          "Que signifie la directive « auto enp0s8 » ?",
          [
            "L'interface reçoit forcément une adresse DHCP",
            "L'interface doit être activée automatiquement",
            "L'interface devient la route par défaut",
            "Le noyau renomme l'interface en eth0",
          ],
          1,
          "auto demande l'activation de l'interface lors de la montée du réseau ; le mode static est défini séparément.",
        ),
        q(
          "Commandes",
          "Pourquoi exécuter ifdown avant de modifier puis ifup après ?",
          [
            "Pour appliquer proprement la nouvelle configuration de l'interface",
            "Pour formater la carte réseau",
            "Pour réinitialiser VirtualBox",
            "Pour modifier le mot de passe SSH",
          ],
          0,
          "Le couple ifdown/ifup retire l'ancien état puis recharge la configuration déclarée pour l'interface.",
        ),
        q(
          "Diagnostic",
          "L'interface est UP mais SSH ne répond pas. Quelle vérification vient logiquement ensuite ?",
          [
            "Vérifier la joignabilité puis le port 22 et le service SSH",
            "Réinstaller immédiatement la VM",
            "Créer un volume logique",
            "Modifier le DNS public",
          ],
          0,
          "Un diagnostic par couches vérifie d'abord le chemin IP, puis le socket 22, puis le service et ses journaux.",
        ),
        q(
          "Virtualisation",
          "Dans ce laboratoire, que représente l'OVA Debian ?",
          [
            "Une image de machine virtuelle prête à importer",
            "Une règle de pare-feu",
            "Un paquet de mise à jour",
            "Une zone DNS",
          ],
          0,
          "Une appliance OVA regroupe la définition et les disques d'une VM afin de reproduire rapidement le même environnement.",
        ),
        q(
          "Sécurité",
          "Quelle pratique est la plus appropriée concernant le compte root ?",
          [
            "L'utiliser pour toutes les activités courantes",
            "Limiter son usage et employer sudo lorsque c'est possible",
            "L'exposer directement sur Internet",
            "Partager son mot de passe dans le support",
          ],
          1,
          "Le moindre privilège réduit l'impact d'une erreur ; les actions administratives doivent être identifiables et limitées.",
        ),
        q(
          "Architecture",
          "Pourquoi conserver un adressage identique pendant tout le fil rouge ?",
          [
            "Pour éviter d'avoir à installer Linux",
            "Pour rendre les tests, noms DNS et configurations de services cohérents",
            "Pour supprimer le besoin de sauvegardes",
            "Pour contourner les permissions Unix",
          ],
          1,
          "Une cible stable évite que chaque nouveau service échoue à cause d'un changement d'adresse sans rapport avec la notion étudiée.",
        ),
        q(
          "Vérification",
          "Quelle affirmation distingue correctement configuration et état réel ?",
          [
            "Un fichier correct prouve toujours que le service fonctionne",
            "Seule une capture d'écran constitue une preuve",
            "Il faut confronter le fichier attendu à une commande d'observation",
            "L'état réel ne peut être vérifié qu'après redémarrage",
          ],
          2,
          "Une configuration décrit le résultat voulu ; une commande comme ip, ss ou systemctl prouve ce qui est effectivement actif.",
        ),
        q(
          "Réseau",
          "Si l'hôte n'a aucune interface dans 192.168.56.0/24, quelle conséquence est probable ?",
          [
            "La connexion directe à 192.168.56.200 échouera",
            "Le noyau Linux ne démarrera plus",
            "Le volume LVM sera plein",
            "BIND créera automatiquement une route",
          ],
          0,
          "Pour joindre directement la VM sur ce réseau privé, l'hôte doit lui aussi disposer d'une interface et d'une adresse dans ce sous-réseau.",
        ),
        q(
          "Exploitation",
          "Quel avantage offre le démarrage de la VM en mode détachable ou en arrière-plan ?",
          [
            "La VM continue à fonctionner sans garder sa fenêtre principale ouverte",
            "La VM n'utilise plus de mémoire",
            "SSH devient inutile",
            "Les disques deviennent persistants",
          ],
          0,
          "Le processus de la VM reste actif ; l'administration peut alors se faire principalement par SSH.",
        ),
        q(
          "Objectifs",
          "Quel ensemble correspond au fil rouge de la formation ?",
          [
            "Stockage, administration système, DNS, Web, pare-feu et messagerie",
            "Développement mobile et impression 3D",
            "Uniquement l'installation de Debian",
            "Bureautique et retouche photo",
          ],
          0,
          "La formation construit progressivement un serveur Linux administré et plusieurs services réseau reliés entre eux.",
        ),
        q(
          "Méthode TSSR",
          "Face à un échec de connexion, quel compte rendu est le plus exploitable ?",
          [
            "« Ça ne marche pas »",
            "Une liste de commandes exécutées sans résultats",
            "Le symptôme, l'hypothèse, la commande de test et le résultat horodaté",
            "Une réinstallation sans diagnostic",
          ],
          2,
          "Une preuve contextualisée permet de reproduire le problème, confirmer ou réfuter l'hypothèse et transmettre efficacement l'incident.",
        ),
      ],
    },

    "01-stockage": {
      id: "01-stockage",
      chapter: "Chapitre 01 · Données",
      title: "Gestion du stockage",
      intro:
        "Testez votre compréhension des couches disque, LVM, système de fichiers, montage et persistance dans fstab.",
      chapterLink: "./",
      questions: [
        q(
          "Observation",
          "Quelle commande présente l'arborescence des périphériques de blocs ?",
          ["lsblk", "lscpu", "journalctl", "ip link"],
          0,
          "lsblk liste les disques, partitions et volumes ; l'option -f ajoute les systèmes de fichiers et UUID.",
        ),
        q(
          "LVM",
          "Dans LVM, quel composant représente la réserve commune d'espace ?",
          ["Le PV", "Le VG", "Le LV", "Le point de montage"],
          1,
          "Un ou plusieurs PV alimentent le Volume Group ; les Logical Volumes sont découpés dans cette réserve.",
        ),
        q(
          "LVM",
          "Quelle séquence respecte l'ordre de création des couches LVM ?",
          [
            "lvcreate, vgcreate, pvcreate",
            "mkfs, mount, pvcreate",
            "pvcreate, vgcreate, lvcreate",
            "vgcreate, mount, fdisk",
          ],
          2,
          "On initialise d'abord le support en PV, on l'ajoute à un VG, puis on crée un LV dans ce groupe.",
        ),
        q(
          "LVM",
          "Quelle commande affiche l'espace libre VFree d'un groupe de volumes ?",
          ["df -h", "du -sh", "vgs", "mount -a"],
          2,
          "vgs observe la réserve LVM ; df mesure une autre couche, celle du système de fichiers monté.",
        ),
        q(
          "Extension",
          "Le VG possède encore 5 Gio libres. Quelle commande agrandit un LV de 2 Gio avec son système de fichiers ?",
          [
            "lvextend --resizefs --size +2G /dev/rootvg/testlv",
            "pvcreate +2G testlv",
            "mkfs -t ext4 +2G",
            "mount --grow testlv",
          ],
          0,
          "lvextend avec --resizefs, ou -r, étend le volume logique puis le système de fichiers compatible.",
        ),
        q(
          "Extension",
          "Le VG est plein. Quelle opération doit précéder l'extension du LV ?",
          [
            "Supprimer /etc/fstab",
            "Ajouter un PV au VG avec vgextend",
            "Réduire le système de fichiers",
            "Changer le point de montage",
          ],
          1,
          "Sans espace libre dans le VG, il faut fournir une nouvelle capacité via un PV puis étendre le groupe.",
        ),
        q(
          "Prudence",
          "Pourquoi la réduction d'un volume est-elle plus risquée que son extension ?",
          [
            "Elle exige souvent de réduire aussi le FS sans détruire de données",
            "Elle change toujours l'adresse IP",
            "Elle désinstalle LVM",
            "Elle ne nécessite aucune sauvegarde",
          ],
          0,
          "Une incohérence entre taille du FS et taille du LV peut détruire les données ; sauvegarde, contrôle et procédure adaptée sont indispensables.",
        ),
        q(
          "Systèmes de fichiers",
          "Quel système de fichiers mentionné ne sait pas rétrécir ?",
          ["ext4", "XFS", "FAT16", "tmpfs"],
          1,
          "XFS peut être agrandi mais pas réduit ; une migration vers un nouveau FS est alors nécessaire pour diminuer la capacité.",
        ),
        q(
          "Systèmes de fichiers",
          "Quel est le rôle de mkfs ?",
          [
            "Créer la structure d'un système de fichiers sur un espace brut",
            "Créer un utilisateur",
            "Monter automatiquement tous les volumes",
            "Afficher les processus",
          ],
          0,
          "Une partition ou un LV reste un espace brut tant qu'un système de fichiers n'y organise pas les données et métadonnées.",
        ),
        q(
          "Montage",
          "Que réalise la commande mount ?",
          [
            "Elle relie un système de fichiers à un dossier de l'arborescence",
            "Elle crée un disque virtuel",
            "Elle convertit un PV en VG",
            "Elle rend toujours le montage persistant",
          ],
          0,
          "Le montage rend le contenu du FS accessible à travers un point de montage ; seul, il ne persiste pas après redémarrage.",
        ),
        q(
          "Persistance",
          "Où déclarer un montage devant être rétabli au démarrage ?",
          ["/etc/fstab", "/etc/passwd", "/proc/mounts", "/boot/vmlinuz"],
          0,
          "/etc/fstab décrit les montages persistants que systemd traduit en unités au démarrage.",
        ),
        q(
          "Identifiants",
          "Pourquoi préférer UUID= à /dev/sdX dans fstab pour un disque classique ?",
          [
            "L'UUID reste lié au FS malgré un changement d'ordre de détection",
            "L'UUID accélère le disque",
            "sdX ne fonctionne jamais sous Linux",
            "L'UUID chiffre les données",
          ],
          0,
          "Le nom sdX peut changer selon l'ordre de détection, tandis que l'UUID identifie le système de fichiers.",
        ),
        q(
          "Validation",
          "Quelle commande vérifie la syntaxe et les références de fstab avant redémarrage ?",
          ["findmnt --verify", "rm /etc/fstab", "lvremove --test", "uname -r"],
          0,
          "findmnt --verify permet de détecter de nombreuses erreurs sans prendre le risque d'un redémarrage en mode d'urgence.",
        ),
        q(
          "Validation",
          "Après modification de fstab, quelle séquence de test est la plus sûre ?",
          [
            "Redémarrer immédiatement",
            "findmnt --verify, daemon-reload, mount -a, puis findmnt",
            "Formater le volume puis couper la VM",
            "Exécuter uniquement df sur /",
          ],
          1,
          "Cette séquence valide, recharge, tente le montage et prouve la source réellement attachée à la cible.",
        ),
        q(
          "Diagnostic",
          "df signale 90 Gio utilisés mais du ne retrouve que 60 Gio visibles. Quelle conclusion est correcte ?",
          [
            "Les deux commandes mesurent exactement la même chose",
            "df mesure le FS, du additionne les fichiers visibles ; il faut poursuivre le diagnostic",
            "Le VG a nécessairement 30 Gio libres",
            "LVM est corrompu",
          ],
          1,
          "Des fichiers supprimés encore ouverts, des montages superposés ou des permissions peuvent expliquer l'écart ; il faut identifier la couche mesurée.",
        ),
        q(
          "Diagnostic",
          "Un démontage répond « target is busy ». Quel premier réflexe adopter ?",
          [
            "Forcer immédiatement avec umount -f",
            "Identifier les processus utilisateurs avec lsof",
            "Supprimer le LV",
            "Recréer le FS",
          ],
          1,
          "lsof +f -- /point permet de trouver les fichiers ouverts ou répertoires courants avant d'arrêter proprement l'activité.",
        ),
        q(
          "Disponibilité",
          "À quoi sert l'option nofail pour un volume de données non critique ?",
          [
            "À continuer le démarrage si ce périphérique manque",
            "À ignorer toutes les erreurs disque",
            "À rendre le FS inscriptible",
            "À désactiver les journaux",
          ],
          0,
          "nofail évite qu'une ressource facultative bloque le boot ; cela ne dispense pas de superviser l'échec de montage.",
        ),
        q(
          "Mesures",
          "Quelle association est correcte ?",
          [
            "df = réserve VG ; vgs = fichiers visibles",
            "du = taille des fichiers visibles ; df = occupation du FS ; vgs = réserve LVM",
            "lsblk = charge CPU ; df = RAM",
            "pvs = sockets réseau ; du = modules",
          ],
          1,
          "Ces commandes observent trois niveaux différents ; annoncer la couche évite les diagnostics contradictoires.",
        ),
        q(
          "Inodes",
          "Un FS refuse de nouveaux petits fichiers alors que df -h indique encore de la place. Que vérifier ?",
          ["df -i", "lscpu", "ip route", "systemctl list-timers"],
          0,
          "L'épuisement des inodes empêche la création de fichiers même si des blocs de données restent disponibles.",
        ),
        q(
          "Preuve",
          "Quelle commande prouve quelle source est réellement montée sur /srv/data ?",
          ["findmnt --target /srv/data", "echo /srv/data", "pwd", "vgcreate /srv/data"],
          0,
          "findmnt interroge l'état courant des montages et affiche la source, le type et les options réellement appliquées.",
        ),
      ],
    },

    "02-administration-systeme": {
      id: "02-administration-systeme",
      chapter: "Chapitre 02 · Système",
      title: "Administration du système Linux",
      intro:
        "Révisez le démarrage, le matériel, les modules, les processus, systemd, les journaux, les performances et la planification.",
      chapterLink: "./",
      questions: [
        q(
          "Démarrage",
          "Quel ordre décrit correctement le démarrage d'un Linux moderne ?",
          [
            "systemd, BIOS, GRUB, noyau",
            "BIOS/UEFI, GRUB, noyau et initramfs, systemd",
            "GRUB, systemd, BIOS, noyau",
            "Noyau, BIOS, initramfs, GRUB",
          ],
          1,
          "Le firmware choisit le support, GRUB charge le noyau, l'initramfs rend la racine accessible puis systemd PID 1 initialise l'espace utilisateur.",
        ),
        q(
          "Démarrage",
          "Quel est le rôle essentiel de l'initramfs ?",
          [
            "Héberger les pages Web",
            "Fournir temporairement les pilotes nécessaires au montage de la vraie racine",
            "Remplacer définitivement /",
            "Planifier les tâches cron",
          ],
          1,
          "Ce mini-système en RAM contient juste assez d'outils et modules pour accéder au stockage racine avant la bascule.",
        ),
        q(
          "Démarrage",
          "Quelle commande montre les unités systemd ayant échoué au boot ?",
          ["systemctl --failed", "lsusb --failed", "df --boot", "crontab -l"],
          0,
          "systemctl --failed fournit une première liste ciblée, à compléter avec status et journalctl pour la cause.",
        ),
        q(
          "Matériel",
          "Une carte PCI apparaît mais aucune interface réseau n'est créée. Quelle commande relie le périphérique à son pilote ?",
          ["lspci -nnk", "free -h", "mailq", "findmnt"],
          0,
          "lspci -nnk affiche les identifiants et les lignes Kernel driver in use / Kernel modules.",
        ),
        q(
          "Matériel",
          "Quelle commande indique si le système tourne dans une VM ?",
          ["systemd-detect-virt", "systemd-analyze blame", "lsmod -v", "nft list ruleset"],
          0,
          "systemd-detect-virt détecte de nombreux hyperviseurs et conteneurs afin de contextualiser le matériel observé.",
        ),
        q(
          "Modules",
          "Quelle différence importante existe entre rmmod et modprobe -r ?",
          [
            "modprobe -r tient compte des dépendances",
            "rmmod installe les dépendances",
            "Les deux formatent le noyau",
            "modprobe -r redémarre toujours",
          ],
          0,
          "modprobe est l'outil de haut niveau et gère les dépendances, contrairement à rmmod qui vise directement un module.",
        ),
        q(
          "Modules",
          "Où placer une option permanente comme « options bonding miimon=100 » ?",
          [
            "Dans /etc/modprobe.d/un-fichier.conf",
            "Dans /etc/fstab",
            "Dans la crontab utilisateur",
            "Dans /var/log/kern.log",
          ],
          0,
          "Les fichiers .conf de /etc/modprobe.d définissent les options et règles appliquées aux chargements de modules.",
        ),
        q(
          "Processus",
          "Quelle relation décrit correctement PID et PPID ?",
          [
            "PPID est le port réseau du processus",
            "PID identifie le processus et PPID son parent",
            "PID indique la priorité uniquement",
            "PPID est toujours égal à 1",
          ],
          1,
          "Chaque processus possède un PID ; le PPID permet de reconstruire sa filiation, sauf cas réadoptés par PID 1.",
        ),
        q(
          "Processus",
          "Quel signal demande proprement à un processus de se terminer ?",
          ["SIGKILL", "SIGTERM", "SIGSTOP", "SIGHUP uniquement"],
          1,
          "SIGTERM laisse au programme la possibilité de fermer ses ressources ; SIGKILL reste un dernier recours non interceptable.",
        ),
        q(
          "systemd",
          "Quelle différence existe entre start et enable ?",
          [
            "start agit maintenant ; enable prépare le démarrage automatique",
            "enable démarre le noyau ; start formate le disque",
            "Ils sont strictement synonymes",
            "start est persistant mais enable ne l'est pas",
          ],
          0,
          "systemctl start change l'état courant ; enable crée les liens de dépendance utilisés aux prochains démarrages.",
        ),
        q(
          "systemd",
          "Après création ou modification d'une unité, quelle commande fait relire ses définitions ?",
          [
            "systemctl daemon-reload",
            "systemctl reboot-now",
            "journalctl --vacuum",
            "modprobe reload",
          ],
          0,
          "daemon-reload recharge les fichiers d'unités ; il faut ensuite redémarrer ou recharger le service concerné si nécessaire.",
        ),
        q(
          "systemd",
          "Un service refuse de démarrer. Quelle paire fournit état puis détails horodatés ?",
          [
            "systemctl status service et journalctl -u service",
            "lsblk et df",
            "free et uptime",
            "dig et host",
          ],
          0,
          "status synthétise le dernier échec ; journalctl -u donne la chronologie complète de l'unité.",
        ),
        q(
          "Journaux",
          "Comment limiter journalctl au démarrage courant ?",
          ["journalctl -b", "journalctl -k -1h", "journalctl --users-only", "journalctl /boot"],
          0,
          "-b sélectionne le boot courant ; -b -1 permet d'examiner le démarrage précédent.",
        ),
        q(
          "Journaux",
          "Quelle commande cible uniquement les messages du noyau dans le journal ?",
          ["journalctl -k", "journalctl -u cron", "systemctl list-units", "dmesg --users"],
          0,
          "journalctl -k filtre le transport noyau, utile pour les pilotes, périphériques, OOM et erreurs bas niveau.",
        ),
        q(
          "Performances",
          "Dans free -h, quelle colonne reflète le mieux la mémoire mobilisable sans swap important ?",
          ["used", "shared", "available", "total"],
          2,
          "Linux utilise la RAM libre comme cache ; available estime ce qui peut être récupéré pour de nouvelles charges.",
        ),
        q(
          "Performances",
          "Dans vmstat, que suggèrent si/so durablement actifs avec peu de mémoire available ?",
          [
            "Une pression mémoire avec échanges de swap",
            "Un problème DNS",
            "Un montage en lecture seule",
            "Une règle nftables absente",
          ],
          0,
          "Les entrées/sorties de swap continues associées aux ralentissements constituent une preuve plus solide que la seule quantité de swap occupée.",
        ),
        q(
          "Performances",
          "Quelle commande distingue un manque de blocs d'un épuisement des inodes ?",
          ["df -h puis df -i", "du puis ip route", "top puis dig", "lsmod puis mailq"],
          0,
          "df -h mesure la capacité en octets ; df -i mesure les structures disponibles pour créer de nouveaux fichiers.",
        ),
        q(
          "Planification",
          "Quel outil convient à une commande unique à exécuter dans dix minutes ?",
          ["cron", "at", "un timer quotidien", "GRUB"],
          1,
          "at planifie une exécution ponctuelle ; cron traite surtout la récurrence.",
        ),
        q(
          "Planification",
          "Dans une crontab utilisateur, que signifie « 0 9 * * 1-5 » ?",
          [
            "Toutes les 9 minutes",
            "À 9 h du lundi au vendredi",
            "Le premier jour de chaque mois à 5 h",
            "À 0 h 09 le week-end",
          ],
          1,
          "Les champs sont minute, heure, jour du mois, mois et jour de semaine.",
        ),
        q(
          "Planification",
          "Quel avantage distingue un timer systemd d'une tâche cron simple ?",
          [
            "Il peut exposer dépendances, code retour et journal par unité",
            "Il n'utilise jamais d'horloge",
            "Il fonctionne sans service associé",
            "Il remplace le noyau",
          ],
          0,
          "Le couple .timer/.service s'intègre au gestionnaire d'unités, aux dépendances, aux états et à journalctl.",
        ),
      ],
    },

    "03-dns-bind9": {
      id: "03-dns-bind9",
      chapter: "Chapitre 03 · Résolution",
      title: "Service DNS avec BIND9",
      intro:
        "Validez les rôles DNS, la structure d'une zone, les contrôles BIND et une méthode de diagnostic qui distingue serveur et client.",
      chapterLink: "./",
      questions: [
        q(
          "Rôles",
          "Quel est le rôle d'un serveur autoritaire pour une zone ?",
          [
            "Conserver la source de vérité de cette zone",
            "Attribuer des adresses par DHCP",
            "Transporter les messages SMTP",
            "Filtrer les paquets entrants",
          ],
          0,
          "Le serveur autoritaire répond à partir des données de zone qu'il héberge, sans devoir demander la réponse à un autre DNS.",
        ),
        q(
          "Rôles",
          "Que fait un résolveur récursif ?",
          [
            "Il cherche la réponse pour le client et peut la mettre en cache",
            "Il crée une partition",
            "Il héberge obligatoirement toutes les zones racine",
            "Il configure l'adresse IP du client",
          ],
          0,
          "La récursion délègue au résolveur la recherche auprès d'autres serveurs ; le TTL borne la durée du cache.",
        ),
        q(
          "Rôles",
          "À quoi sert un forwarder configuré dans BIND ?",
          [
            "À relayer certaines requêtes vers un DNS externe",
            "À transférer les fichiers de la zone par FTP",
            "À ouvrir le port 80",
            "À créer les comptes locaux",
          ],
          0,
          "Le forwarder reçoit les requêtes que le serveur choisit de ne pas résoudre lui-même, par exemple les noms Internet.",
        ),
        q(
          "Installation",
          "Quel paquet fournit les outils DNS tels que dig dans le cours ?",
          ["bind9-dnsutils", "apache2-utils", "lvm2", "mailutils"],
          0,
          "bind9 installe le serveur ; bind9-dnsutils apporte notamment les outils d'interrogation et de diagnostic.",
        ),
        q(
          "Configuration",
          "Dans quel fichier déclare-t-on généralement une zone locale BIND sous Debian ?",
          [
            "/etc/bind/named.conf.local",
            "/etc/fstab",
            "/etc/postfix/main.cf",
            "/var/www/index.php",
          ],
          0,
          "named.conf.local est prévu pour les déclarations locales, tandis que named.conf.options contient les options globales.",
        ),
        q(
          "Enregistrements",
          "Quel type associe directement un nom à une adresse IPv4 ?",
          ["A", "MX", "CNAME", "PTR"],
          0,
          "Un enregistrement A porte une adresse IPv4 ; AAAA est son équivalent pour IPv6.",
        ),
        q(
          "Enregistrements",
          "Quel type indique le serveur chargé de recevoir les courriels d'un domaine ?",
          ["SOA", "NS", "MX", "TXT"],
          2,
          "MX référence un nom de serveur de messagerie avec une préférence ; ce nom doit ensuite être résolu en adresse.",
        ),
        q(
          "Enregistrements",
          "Que représente un CNAME ?",
          [
            "Un alias vers un autre nom canonique",
            "Une adresse IPv4 chiffrée",
            "Le numéro de série de zone",
            "Une route par défaut",
          ],
          0,
          "CNAME fait d'un nom un alias ; la cible est un nom DNS, pas directement une adresse IP.",
        ),
        q(
          "Zone",
          "Pourquoi le point final est-il important après un nom complet dans un fichier de zone ?",
          [
            "Il empêche l'ajout automatique du nom de la zone",
            "Il active DNSSEC",
            "Il remplace le TTL",
            "Il commente la ligne",
          ],
          0,
          "Sans point final, BIND considère souvent le nom relatif et lui ajoute l'origine de zone, ce qui peut doubler le domaine.",
        ),
        q(
          "Zone",
          "Quel champ du SOA doit être incrémenté après une modification distribuée de la zone ?",
          ["Le port", "Le serial", "Le masque", "Le handle"],
          1,
          "Le numéro de série permet notamment aux serveurs secondaires de détecter qu'une version plus récente existe.",
        ),
        q(
          "Validation",
          "Quelle commande vérifie la syntaxe globale de la configuration BIND ?",
          ["named-checkconf", "named-checkzone uniquement", "dig +trace", "rndc status-zone"],
          0,
          "named-checkconf analyse les fichiers de configuration inclus et détecte les erreurs globales avant application.",
        ),
        q(
          "Validation",
          "Quelle commande valide les données d'une zone précise ?",
          [
            "named-checkzone nom-zone fichier-zone",
            "systemctl enable zone",
            "host --write-zone",
            "nft check dns",
          ],
          0,
          "named-checkzone associe le nom attendu au fichier et contrôle notamment la syntaxe et la cohérence de la zone.",
        ),
        q(
          "Application",
          "Après validation, quelle commande recharge proprement les zones dans BIND ?",
          ["rndc reload", "mkfs reload", "apache2ctl reload", "ip reload dns"],
          0,
          "rndc pilote le démon named et recharge les données sans imposer un redémarrage complet du serveur.",
        ),
        q(
          "Test ciblé",
          "Que teste précisément « dig @192.168.56.200 www.dawan-s35.local A » ?",
          [
            "Le serveur DNS 192.168.56.200 directement pour un enregistrement A",
            "Le DNS configuré par défaut sur le client",
            "Le serveur Web en HTTP",
            "La route NAT de VirtualBox uniquement",
          ],
          0,
          "La syntaxe @serveur force la cible DNS et isole le fonctionnement de BIND de la configuration du résolveur client.",
        ),
        q(
          "Test client",
          "Pourquoi compléter un dig @serveur réussi par un dig sans @ depuis le poste client ?",
          [
            "Pour vérifier que le client utilise effectivement le bon DNS",
            "Pour changer le serial",
            "Pour créer automatiquement un MX",
            "Pour désactiver le cache",
          ],
          0,
          "Le service peut fonctionner directement alors que le poste interroge un autre résolveur ou possède une configuration DNS incorrecte.",
        ),
        q(
          "Interprétation",
          "Dans la réponse dig, que signifie le drapeau aa ?",
          [
            "Réponse autoritaire",
            "Adresse absente",
            "Authentification acceptée",
            "Alias automatique",
          ],
          0,
          "aa signifie Authoritative Answer : le serveur répond comme autorité pour le nom demandé.",
        ),
        q(
          "Interprétation",
          "Que signifie NXDOMAIN ?",
          [
            "Le nom demandé n'existe pas dans l'espace interrogé",
            "Le serveur ne répond pas au port 53",
            "La réponse est forcément en cache",
            "La zone est signée",
          ],
          0,
          "NXDOMAIN est une réponse DNS valide indiquant l'inexistence du nom ; un timeout correspond à un problème différent.",
        ),
        q(
          "Réseau",
          "Quelle observation prouve que named écoute sur le port DNS ?",
          ["ss -lunpt avec une entrée sur :53", "lsblk -f", "df -i", "systemctl list-timers"],
          0,
          "DNS utilise principalement UDP 53 et aussi TCP 53 ; ss permet d'observer les sockets réellement ouverts.",
        ),
        q(
          "Diagnostic",
          "Le compteur du pare-feu augmente et dig reçoit SERVFAIL. Où poursuivre en priorité ?",
          [
            "Dans la validation de zone et les journaux BIND",
            "Dans le partitionnement du client",
            "Dans la configuration Apache",
            "Dans le mot de passe de l'utilisateur",
          ],
          0,
          "Le paquet atteint le serveur et une réponse DNS revient ; SERVFAIL oriente vers le traitement DNS, ses données ou ses dépendances.",
        ),
        q(
          "Méthode TSSR",
          "Quelle séquence de mise en production limite le risque d'une zone invalide ?",
          [
            "Modifier, redémarrer, puis éventuellement lire les logs",
            "Modifier, named-checkconf, named-checkzone, reload, dig ciblé",
            "Supprimer le cache et réinstaller Debian",
            "Tester uniquement avec ping",
          ],
          1,
          "On valide d'abord statiquement, on applique ensuite, puis on prouve le résultat par une requête ciblée et l'observation des journaux.",
        ),
      ],
    },

    "04-serveur-web-lamp": {
      id: "04-serveur-web-lamp",
      chapter: "Chapitre 04 · Application",
      title: "Serveur Web LAMP",
      intro:
        "Vérifiez votre compréhension d'Apache, des virtual hosts, de PHP, de MariaDB et du diagnostic couche par couche.",
      chapterLink: "./",
      questions: [
        q(
          "Architecture",
          "Que signifie l'acronyme LAMP dans ce chapitre ?",
          [
            "Linux, Apache, MariaDB, PHP",
            "Linux, Active Directory, Mail, Python",
            "LAN, Apache, Modem, Proxy",
            "Linux, API, Monitoring, Postfix",
          ],
          0,
          "La pile associe l'OS Linux, le serveur HTTP Apache, la base MariaDB et le langage côté serveur PHP.",
        ),
        q(
          "Flux",
          "Quel composant reçoit en premier une requête HTTP du navigateur ?",
          ["MariaDB", "Apache", "PHP directement", "systemd-resolved"],
          1,
          "Après la résolution DNS et la connexion TCP, Apache accepte la requête puis sert un fichier ou transmet le script au moteur PHP.",
        ),
        q(
          "Installation",
          "Quel paquet relie PHP à MariaDB dans la commande d'installation proposée ?",
          ["php-mysql", "bind9-dnsutils", "dovecot-imapd", "xfsprogs"],
          0,
          "php-mysql fournit les extensions nécessaires, notamment mysqli/PDO MySQL, pour qu'un script PHP dialogue avec MariaDB.",
        ),
        q(
          "Apache",
          "Dans quel répertoire Debian place-t-on les virtual hosts disponibles ?",
          [
            "/etc/apache2/sites-available",
            "/etc/apache2/sites-enabled uniquement",
            "/var/lib/mysql",
            "/home/www-data",
          ],
          0,
          "Les définitions résident dans sites-available ; a2ensite crée un lien dans sites-enabled pour les activer.",
        ),
        q(
          "Apache",
          "Que fait a2ensite dawan-s35.conf ?",
          [
            "Active le virtual host via un lien dans sites-enabled",
            "Crée une base SQL",
            "Ouvre automatiquement le pare-feu",
            "Ajoute un enregistrement DNS",
          ],
          0,
          "a2ensite gère le lien symbolique ; il faut ensuite valider la configuration et recharger Apache.",
        ),
        q(
          "Validation",
          "Quelle commande contrôle la syntaxe Apache avant rechargement ?",
          ["apache2ctl configtest", "php -m", "mysql_secure_installation", "curl --write-config"],
          0,
          "configtest doit renvoyer Syntax OK avant que la nouvelle configuration soit appliquée.",
        ),
        q(
          "Application",
          "Pourquoi préférer systemctl reload apache2 après une configuration validée ?",
          [
            "Pour relire la configuration en limitant l'interruption",
            "Pour formater DocumentRoot",
            "Pour redémarrer MariaDB",
            "Pour modifier le DNS",
          ],
          0,
          "Un reload demande au service de relire sa configuration sans l'arrêt complet associé à un restart, lorsque le service le prend en charge.",
        ),
        q(
          "Virtual host",
          "Comment Apache choisit-il entre plusieurs sites partageant IP et port ?",
          [
            "Grâce à l'en-tête HTTP Host comparé à ServerName/ServerAlias",
            "Grâce au nom de l'utilisateur Linux",
            "Au hasard",
            "Avec le numéro de série DNS",
          ],
          0,
          "Le virtual hosting par nom utilise l'en-tête Host envoyé par le client pour sélectionner le bloc correspondant.",
        ),
        q(
          "Test ciblé",
          "Pourquoi utiliser curl avec « -H 'Host: www.dawan-s35.local' » vers l'adresse IP ?",
          [
            "Pour tester le vhost indépendamment de la résolution DNS",
            "Pour créer le domaine DNS",
            "Pour démarrer Apache",
            "Pour chiffrer automatiquement HTTP",
          ],
          0,
          "Cette méthode fixe l'en-tête de sélection tout en contactant directement l'IP, ce qui isole Apache du DNS.",
        ),
        q(
          "Diagnostic",
          "Tester seulement http://192.168.56.200 affiche le site par défaut. Quelle conclusion est juste ?",
          [
            "Le vhost est forcément cassé",
            "Il faut tester avec le nom ou un en-tête Host correspondant",
            "MariaDB doit être réinstallée",
            "Le port 80 est fermé",
          ],
          1,
          "Sans Host correspondant, Apache peut choisir le premier vhost ; cela ne réfute pas le fonctionnement du site nommé.",
        ),
        q(
          "MariaDB",
          "Quelle instruction accorde les droits uniquement sur la base dawan_s35 à dawan_user ?",
          [
            "GRANT ALL PRIVILEGES ON dawan_s35.* TO 'dawan_user'@'localhost'",
            "GRANT ROOT ON * TO everyone",
            "CHMOD DATABASE 777",
            "ALLOW SQL IN nftables",
          ],
          0,
          "Le périmètre base.* et l'hôte localhost appliquent le moindre privilège mieux qu'un compte administrateur global.",
        ),
        q(
          "Sécurité",
          "Pourquoi l'application ne devrait-elle pas se connecter avec le compte root MariaDB ?",
          [
            "Pour limiter l'impact d'une compromission ou erreur applicative",
            "Parce que root ne peut jamais utiliser SQL",
            "Parce qu'Apache exige un compte DNS",
            "Pour accélérer PHP",
          ],
          0,
          "Un compte dédié ne possède que les privilèges nécessaires à sa base et réduit fortement le rayon d'impact.",
        ),
        q(
          "PHP",
          "Quelle commande vérifie que l'extension mysqli est chargée ?",
          ["php -m | grep -i mysqli", "lsmod | grep php", "dig mysqli", "nft list mysqli"],
          0,
          "php -m liste les modules PHP actifs ; l'absence de mysqli explique une erreur de classe ou de fonction lors de la connexion SQL.",
        ),
        q(
          "Permissions",
          "Sous quelle identité Apache s'exécute-t-il généralement sur Debian ?",
          ["www-data", "rootvg", "named", "postfix uniquement"],
          0,
          "www-data doit pouvoir lire le contenu, mais ne devrait écrire que dans les répertoires explicitement prévus.",
        ),
        q(
          "Permissions",
          "Quelle stratégie respecte le mieux le moindre privilège sur le code du site ?",
          [
            "Tout placer en 0777",
            "Lecture pour www-data et écriture limitée aux dossiers qui en ont besoin",
            "Exécuter Apache en root",
            "Désactiver toutes les permissions",
          ],
          1,
          "Rendre tout le site inscriptible par le processus Web facilite la persistance après compromission et les modifications accidentelles.",
        ),
        q(
          "Sockets",
          "Quelle commande vérifie qu'un processus écoute effectivement sur TCP 80 ?",
          ["ss -lntp | grep ':80'", "df -hT /var/www", "named-checkconf", "mailq"],
          0,
          "ss observe les sockets en écoute et, avec les droits nécessaires, le processus associé.",
        ),
        q(
          "DNS",
          "Quelle commande vérifie la résolution du nom Web par le mécanisme normal du système ?",
          ["getent hosts www.dawan-s35.local", "lvdisplay www", "journalctl -k www", "crontab -l"],
          0,
          "getent utilise la configuration NSS du système et teste donc la résolution réellement utilisée par les applications.",
        ),
        q(
          "Logs",
          "Où chercher une erreur spécifique au virtual host configuré avec son ErrorLog ?",
          [
            "Dans /var/log/apache2/dawan-s35-error.log",
            "Dans /etc/fstab",
            "Dans /proc/cpuinfo",
            "Dans la zone inverse DNS uniquement",
          ],
          0,
          "Le journal d'erreurs du vhost contient les problèmes de chemin, permissions, PHP et traitement des requêtes.",
        ),
        q(
          "Diagnostic",
          "La page statique répond, mais le script PHP signale « Class mysqli not found ». Quelle couche est en cause ?",
          [
            "Le module PHP d'accès à MariaDB",
            "La résolution DNS",
            "Le socket HTTP",
            "Le chargeur GRUB",
          ],
          0,
          "Apache et HTTP fonctionnent déjà ; l'erreur nomme une extension PHP manquante ou inactive.",
        ),
        q(
          "Méthode TSSR",
          "Quel ordre de test localise le mieux une panne LAMP ?",
          [
            "DNS, socket HTTP, sélection du vhost, PHP, connexion SQL",
            "SQL, redémarrage complet, puis DNS",
            "Permissions 0777, pare-feu flush, réinstallation",
            "Tester uniquement depuis le navigateur",
          ],
          0,
          "Chaque test valide une couche avant de monter dans la pile, ce qui évite de modifier MariaDB pour une panne de DNS ou de vhost.",
        ),
      ],
    },

    "05-pare-feu-nftables": {
      id: "05-pare-feu-nftables",
      chapter: "Chapitre 05 · Protection",
      title: "Pare-feu nftables",
      intro:
        "Évaluez votre maîtrise des tables, chaînes, états de connexion, règles persistantes et preuves par compteurs.",
      chapterLink: "./",
      questions: [
        q(
          "Chaînes",
          "Quelle chaîne filtre un paquet destiné au serveur lui-même ?",
          ["input", "output", "forward", "preroute-web"],
          0,
          "input traite le trafic dont la destination locale est la machine ; le trafic routé vers une autre machine suit forward.",
        ),
        q(
          "Chaînes",
          "Quelle chaîne concerne les paquets émis par un processus local ?",
          ["input", "output", "forward", "ingress uniquement"],
          1,
          "output voit le trafic créé localement avant sa sortie ; input concerne les paquets reçus pour la machine.",
        ),
        q(
          "Chaînes",
          "Quand la chaîne forward est-elle utilisée ?",
          [
            "Quand la machine route un paquet entre interfaces",
            "Pour tous les processus locaux",
            "Uniquement pour les journaux",
            "Pour monter un système de fichiers",
          ],
          0,
          "forward s'applique au trafic qui traverse la machine sans lui être destiné, cas typique d'un routeur ou d'une passerelle.",
        ),
        q(
          "Organisation",
          "Dans nftables, comment s'organisent les objets du plus large au plus précis ?",
          [
            "Table, chaîne, règle",
            "Règle, table, processus",
            "Chaîne, disque, table",
            "Service, paquet, LV",
          ],
          0,
          "Les tables regroupent des chaînes ; chaque chaîne contient une suite ordonnée de règles.",
        ),
        q(
          "Observation",
          "Quelle commande affiche l'ensemble des règles actuellement chargées ?",
          [
            "nft list ruleset",
            "nft show config-file",
            "iptables --install",
            "systemctl cat network",
          ],
          0,
          "nft list ruleset interroge l'état actif du noyau, qui peut différer du fichier persistant.",
        ),
        q(
          "Prudence",
          "Pourquoi « nft flush ruleset » est-il dangereux dans une session SSH distante ?",
          [
            "Il peut supprimer les règles assurant ou encadrant l'accès",
            "Il formate le disque",
            "Il arrête le noyau",
            "Il modifie le mot de passe SSH",
          ],
          0,
          "Vider tout le ruleset change immédiatement la politique active ; une erreur ultérieure peut laisser la machine exposée ou inaccessible.",
        ),
        q(
          "Validation",
          "Quelle commande vérifie un fichier nftables sans l'appliquer ?",
          [
            "nft --check --file /etc/nftables.conf",
            "nft flush --dry-run",
            "systemctl enable --test",
            "ss --check-firewall",
          ],
          0,
          "--check analyse la syntaxe et les objets sans remplacer le jeu de règles actif.",
        ),
        q(
          "Application",
          "Quelle commande charge /etc/nftables.conf dans le noyau ?",
          ["nft -f /etc/nftables.conf", "mount -a", "named-checkconf", "postqueue -f"],
          0,
          "-f exécute les instructions du fichier ; il faut ensuite relire le ruleset actif et tester les flux attendus.",
        ),
        q(
          "Persistance",
          "Une règle ajoutée avec nft add rule disparaît après redémarrage. Pourquoi ?",
          [
            "Elle n'a pas été inscrite dans la configuration rechargée au boot",
            "Les règles nftables durent toujours une minute",
            "Le port est géré par DNS",
            "La commande add ne modifie jamais l'état actif",
          ],
          0,
          "L'ajout à chaud affecte le noyau courant ; le service recharge /etc/nftables.conf au prochain démarrage.",
        ),
        q(
          "Ordre",
          "Comment nftables traite-t-il les règles d'une chaîne ?",
          [
            "Dans l'ordre, jusqu'à un verdict terminal pertinent",
            "Toujours par numéro de port croissant",
            "En choisissant une règle au hasard",
            "Uniquement de la dernière vers la première",
          ],
          0,
          "Une règle accept/drop/reject peut arrêter l'évaluation ; placer une règle après un drop général peut la rendre inatteignable.",
        ),
        q(
          "État",
          "Que permet « ct state established,related accept » ?",
          [
            "Le trafic de retour des connexions déjà autorisées",
            "Toutes les nouvelles connexions entrantes",
            "Uniquement les paquets invalides",
            "La création d'une table",
          ],
          0,
          "Le suivi de connexion reconnaît les échanges existants et les flux liés, ce qui autorise les réponses sans ouvrir tous les ports.",
        ),
        q(
          "État",
          "Pourquoi placer « ct state invalid drop » tôt dans la chaîne ?",
          [
            "Pour écarter les paquets non rattachables à un état cohérent",
            "Pour autoriser tous les paquets UDP",
            "Pour désactiver le suivi de connexion",
            "Pour créer un compteur système",
          ],
          0,
          "L'état invalid indique que conntrack ne peut pas associer correctement le paquet à une connexion.",
        ),
        q(
          "ICMP",
          "Pourquoi ne faut-il pas bloquer aveuglément ICMP et ICMPv6 ?",
          [
            "Ils transportent des erreurs réseau et des fonctions indispensables, notamment en IPv6",
            "Ils servent uniquement à HTTP",
            "Ils remplacent SSH",
            "Ils ne traversent jamais un réseau",
          ],
          0,
          "Au-delà de ping, ICMP signale des erreurs et participe à PMTU ; ICMPv6 est essentiel à la découverte des voisins.",
        ),
        q(
          "Handles",
          "À quoi sert l'option -a lors de l'affichage du ruleset ?",
          [
            "Afficher les handles permettant d'identifier une règle",
            "Activer toutes les règles",
            "Ajouter automatiquement SSH",
            "Afficher uniquement IPv4",
          ],
          0,
          "Le handle est l'identifiant utilisé notamment par nft delete rule ... handle NUMERO.",
        ),
        q(
          "Compteurs",
          "Quel est l'intérêt du mot-clé counter dans une règle ?",
          [
            "Prouver par paquets et octets qu'elle est rencontrée",
            "Accélérer automatiquement le service",
            "Créer une sauvegarde",
            "Attribuer une adresse IP",
          ],
          0,
          "Comparer le compteur avant et après un test montre si le trafic suit réellement cette règle.",
        ),
        q(
          "Diagnostic",
          "Le compteur de la règle TCP 80 reste à zéro pendant un curl. Quelle hypothèse est prioritaire ?",
          [
            "Le paquet ne suit pas cette règle ou cette chaîne",
            "PHP est forcément absent",
            "MariaDB refuse le mot de passe",
            "Le disque est plein",
          ],
          0,
          "Il faut vérifier famille IP, adresse cible, interface, chemin et ordre des règles avant d'accuser l'application.",
        ),
        q(
          "Diagnostic",
          "Le compteur TCP 80 augmente, mais curl reçoit « connection refused ». Où regarder ensuite ?",
          [
            "Le socket d'écoute et le service Web",
            "Le serial DNS uniquement",
            "La taille du VG",
            "La crontab root",
          ],
          0,
          "Le paquet atteint la règle ; un refus indique généralement qu'aucun service n'écoute ou qu'un rejet provient plus haut dans la pile.",
        ),
        q(
          "Sécurité",
          "Quelle précaution réduit le risque de se couper l'accès lors d'un changement distant ?",
          [
            "Conserver une console et une seconde session, avec un retour arrière préparé",
            "Fermer la seule session avant le test",
            "Faire un flush sans sauvegarde",
            "Désactiver les compteurs",
          ],
          0,
          "Une voie hors bande ou console hyperviseur et un rollback temporisé rendent l'intervention récupérable.",
        ),
        q(
          "Familles",
          "Quel avantage offre une table de famille inet pour un filtrage simple ?",
          [
            "Elle peut traiter IPv4 et IPv6 dans les mêmes chaînes",
            "Elle ne traite que le trafic local",
            "Elle remplace le routage",
            "Elle chiffre les paquets",
          ],
          0,
          "La famille inet permet de mutualiser de nombreuses règles, tout en gardant des expressions ip ou ip6 lorsque nécessaire.",
        ),
        q(
          "Méthode TSSR",
          "Quelle séquence fournit la meilleure preuve après une modification ?",
          [
            "Contrôle syntaxique, sauvegarde, application, lecture du ruleset, test du flux et compteurs",
            "Application directe puis fermeture SSH",
            "Redémarrage sans test",
            "Capture du fichier seulement",
          ],
          0,
          "Cette démarche distingue intention, état actif et résultat réseau mesuré, tout en gardant une possibilité de retour arrière.",
        ),
      ],
    },

    "06-messagerie": {
      id: "06-messagerie",
      chapter: "Chapitre 06 · Service complet",
      title: "Service de messagerie",
      intro:
        "Suivez un courrier de SMTP à Maildir puis IMAP, en distinguant clairement les rôles de Postfix, Dovecot et du webmail.",
      chapterLink: "./",
      questions: [
        q(
          "Architecture",
          "Quel est le rôle principal de Postfix dans le laboratoire ?",
          [
            "Recevoir et envoyer les courriels via SMTP",
            "Afficher les pages PHP",
            "Fournir la résolution DNS",
            "Monter les volumes LVM",
          ],
          0,
          "Postfix est le MTA : il prend en charge le transport SMTP et la remise vers la boîte locale configurée.",
        ),
        q(
          "Architecture",
          "Quel rôle remplit Dovecot ?",
          [
            "Donner accès aux boîtes via IMAP",
            "Filtrer les paquets nftables",
            "Créer les zones DNS",
            "Exécuter PHP",
          ],
          0,
          "Dovecot expose les messages stockés, ici dans Maildir, aux clients utilisant IMAP.",
        ),
        q(
          "Architecture",
          "Que fait le webmail RainLoop dans cette chaîne ?",
          [
            "Il agit comme un client Web utilisant IMAP et SMTP",
            "Il remplace le serveur DNS",
            "Il stocke les volumes physiques",
            "Il compile le noyau",
          ],
          0,
          "Le webmail fournit une interface ; en arrière-plan, il se connecte aux mêmes services que tout autre client mail.",
        ),
        q(
          "Postfix",
          "Quel paramètre définit le nom complet du serveur Postfix ?",
          ["myhostname", "home_mailbox", "mail_location", "ServerName"],
          0,
          "myhostname identifie le MTA, par exemple mail.dawan-s35.local.",
        ),
        q(
          "Postfix",
          "Que produit « home_mailbox = Maildir/ » ?",
          [
            "Une remise au format Maildir dans le domicile du destinataire",
            "Une base SQL nommée Maildir",
            "Un relais DNS",
            "Une boîte unique pour tous les utilisateurs",
          ],
          0,
          "La barre finale indique un répertoire Maildir, généralement ~/Maildir, contenant notamment new, cur et tmp.",
        ),
        q(
          "Comptes",
          "Sans annuaire externe, à quoi correspond une boîte locale dans ce laboratoire ?",
          [
            "À un utilisateur Linux local",
            "À un virtual host Apache",
            "À un volume logique",
            "À une règle input",
          ],
          0,
          "Les comptes alice et bob sont des comptes système dont le domicile reçoit la structure Maildir.",
        ),
        q(
          "Dovecot",
          "Quel réglage indique à Dovecot le format et l'emplacement des boîtes ?",
          [
            "mail_location = maildir:~/Maildir",
            "mydestination = Maildir",
            "DocumentRoot = Maildir",
            "zone Maildir local",
          ],
          0,
          "mail_location doit correspondre à la remise choisie dans Postfix pour que les deux services voient les mêmes messages.",
        ),
        q(
          "Cohérence",
          "Postfix livre dans ~/Maildir mais Dovecot cherche /var/mail/user. Quel symptôme est probable ?",
          [
            "Le message est livré mais invisible en IMAP",
            "Le DNS ne démarre plus",
            "Le port 80 devient HTTPS",
            "Le VG s'étend automatiquement",
          ],
          0,
          "Les deux composants fonctionnent séparément mais ne partagent pas le même stockage ; il faut aligner leurs configurations.",
        ),
        q(
          "Test",
          "Quelle commande envoie un message local simple à bob dans le cours ?",
          [
            "echo 'Ceci est un test' | mail -s 'Sujet' bob@dawan-s35.local",
            "dig bob MX",
            "curl smtp://bob",
            "nft add mail bob",
          ],
          0,
          "mailutils fournit une manière simple de soumettre un message à la chaîne locale sans dépendre du webmail.",
        ),
        q(
          "Preuve",
          "Quelle observation prouve la remise physique du message dans la boîte de bob ?",
          [
            "Un nouveau fichier sous /home/bob/Maildir/new",
            "Une réponse ping",
            "Un fichier dans /var/www",
            "Une règle nftables sans compteur",
          ],
          0,
          "Maildir stocke chaque nouveau message dans un fichier distinct du sous-répertoire new.",
        ),
        q(
          "SMTP",
          "Quel port est historiquement utilisé pour le transport SMTP entre serveurs ?",
          ["25", "53", "80", "143"],
          0,
          "TCP 25 sert au transport SMTP ; 587 est couramment utilisé pour la soumission authentifiée des clients.",
        ),
        q(
          "IMAP",
          "Quelle paire associe correctement IMAP non chiffré et IMAPS ?",
          ["143 et 993", "25 et 587", "53 et 853", "80 et 443"],
          0,
          "IMAP écoute classiquement sur 143, tandis qu'IMAPS encapsulé dans TLS utilise 993.",
        ),
        q(
          "Validation",
          "Quelle commande vérifie la configuration Postfix ?",
          ["postfix check", "apache2ctl configtest", "named-checkzone", "findmnt --verify"],
          0,
          "postfix check détecte des problèmes de configuration et de permissions ; postconf -n affiche les réglages non par défaut.",
        ),
        q(
          "Validation",
          "Quelle commande affiche la configuration Dovecot effectivement calculée ?",
          ["doveconf -n", "postconf -n", "dig -n", "nft -n"],
          0,
          "doveconf -n synthétise les paramètres non par défaut et aide à repérer le fichier réellement pris en compte.",
        ),
        q(
          "Dialogue SMTP",
          "Après RCPT TO dans un dialogue SMTP, quelle commande annonce le contenu du message ?",
          ["DATA", "BODY", "SEND", "MAILDIR"],
          0,
          "DATA ouvre la phase de contenu ; une ligne contenant seulement un point termine le message.",
        ),
        q(
          "Codes SMTP",
          "Que signifie en général un code SMTP commençant par 4 ?",
          [
            "Une erreur temporaire pouvant justifier une nouvelle tentative",
            "Un succès définitif",
            "Un refus permanent",
            "Une réponse IMAP",
          ],
          0,
          "Les codes 2xx signalent le succès, 4xx une difficulté temporaire et 5xx un refus permanent.",
        ),
        q(
          "File d'attente",
          "Quelle commande affiche la file d'attente Postfix ?",
          ["mailq ou postqueue -p", "lsblk -q", "journalctl --queue-only", "doveconf -q"],
          0,
          "La file contient les messages pas encore remis ou transmis et fournit les identifiants nécessaires au suivi.",
        ),
        q(
          "Traçabilité",
          "Pourquoi conserver l'identifiant de file affiché par Postfix ?",
          [
            "Pour corréler les lignes concernant le même message dans les journaux",
            "Pour se connecter en IMAP",
            "Pour calculer l'adresse IP",
            "Pour identifier un LV",
          ],
          0,
          "Cet identifiant suit le message dans les étapes Postfix et évite de confondre plusieurs échanges simultanés.",
        ),
        q(
          "Sécurité",
          "Pourquoi l'authentification en clair sur IMAP 143 n'est-elle acceptable que dans un labo isolé ?",
          [
            "Les identifiants peuvent être interceptés sans TLS",
            "IMAP chiffre toujours deux fois",
            "Le port 143 bloque les mots de passe",
            "Postfix remplace automatiquement TLS",
          ],
          0,
          "Sur un réseau non fiable, il faut protéger l'authentification et les messages avec TLS et une configuration de certificats correcte.",
        ),
        q(
          "Diagnostic",
          "Quel ordre suit réellement un message local consulté par webmail ?",
          [
            "Client/RainLoop, Postfix SMTP, Maildir, Dovecot IMAP, affichage client",
            "Dovecot, DNS, LVM, Postfix",
            "Apache, nftables, GRUB, Maildir",
            "MariaDB, BIND, cron, IMAP",
          ],
          0,
          "Séparer transport, remise, stockage et consultation permet de localiser précisément l'étape où le message disparaît.",
        ),
      ],
    },
  }
})()
